# Generated by Django 2.2.7 on 2020-01-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/en/b/b5/Harry-film-logo.png', max_length=300),
        ),
        migrations.AddField(
            model_name='character',
            name='wiki',
            field=models.CharField(default='https://en.wikipedia.org/wiki/Harry_Potter_(film_series)', max_length=300),
        ),
    ]
