# Generated by Django 2.2.7 on 2020-01-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20200114_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, upload_to='all_char'),
        ),
    ]
