# Generated by Django 2.2.7 on 2020-01-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_books_movies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='book',
        ),
        migrations.RenameModel(
            old_name='movies',
            new_name='movie',
        ),
    ]
