# Generated by Django 2.2.7 on 2020-01-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_auto_20200119_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(default='1998', max_length=4),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default='2000', max_length=4),
        ),
    ]
