# Generated by Django 2.2.7 on 2020-01-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to='all_char'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default='7.0', max_length=4),
        ),
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.CharField(default='op', max_length=2000),
        ),
    ]
