# Generated by Django 2.2.7 on 2020-01-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_auto_20200120_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.CharField(default='https://en.wikipedia.org/wiki/Harry_Potter_(film_series)', max_length=300),
        ),
    ]
