# Generated by Django 2.2.7 on 2020-01-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_movie_imdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.CharField(default='op', max_length=3000),
        ),
    ]
