# Generated by Django 2.2.7 on 2020-01-26 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_auto_20200124_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
    ]
