# Generated by Django 2.2.7 on 2020-01-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_remove_movie_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='about',
            field=models.CharField(max_length=300),
        ),
    ]
