# Generated by Django 2.2.7 on 2020-01-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_auto_20200128_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ebook', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='all_char')),
            ],
        ),
    ]
